import env from "../env";

export const ENV_CONFIGS = {
  API_KEY: env.API_KEY,
  WEBHOOK_API_KEY: env.WEBHOOK_API_KEY,
  EMAIL_FROM: env.EMAIL_FROM,
  EMAIL_REPLY_TO: env.EMAIL_REPLY_TO,
  EMAIL_WELCOME_PASS: env.EMAIL_WELCOME_PASS,
};
